; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "بِالْعَرَبِيّ V4.0"
#define MyAppVersion "4.0"
#define MyAppPublisher "CodiaeumTech"
#define MyAppExeName "saged_online_platform.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{0905468A-E14E-44A3-985B-0801EA4C12C5}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={userdocs}\{#MyAppName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=F:\My_Works\Flutter_Projects\koraiem_app\saged_online_platform\installesrs
OutputBaseFilename=بِالْعَرَبِيّ_setup V4.0
SetupIconFile=F:\My_Works\Flutter_Projects\koraiem_app\saged_online_platform\logo.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "F:\My_Works\Flutter_Projects\koraiem_app\saged_online_platform\build\windows\x64\runner\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "F:\My_Works\Flutter_Projects\koraiem_app\saged_online_platform\build\windows\x64\runner\Release\saged_online_platform.exp"; DestDir: "{app}"; Flags: ignoreversion
Source: "F:\My_Works\Flutter_Projects\koraiem_app\saged_online_platform\build\windows\x64\runner\Release\saged_online_platform.lib"; DestDir: "{app}"; Flags: ignoreversion


Source: "F:\My_Works\Flutter_Projects\koraiem_app\saged_online_platform\build\windows\x64\runner\Release\flutter_windows.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "F:\My_Works\Flutter_Projects\koraiem_app\saged_online_platform\build\windows\x64\runner\Release\flutter_inappwebview_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "F:\My_Works\Flutter_Projects\koraiem_app\saged_online_platform\build\windows\x64\runner\Release\cloud_firestore_plugin.lib"; DestDir: "{app}"; Flags: ignoreversion
Source: "F:\My_Works\Flutter_Projects\koraiem_app\saged_online_platform\build\windows\x64\runner\Release\firebase_core_plugin.lib"; DestDir: "{app}"; Flags: ignoreversion
Source: "F:\My_Works\Flutter_Projects\koraiem_app\saged_online_platform\build\windows\x64\runner\Release\firebase_auth_plugin.lib"; DestDir: "{app}"; Flags: ignoreversion
Source: "F:\My_Works\Flutter_Projects\koraiem_app\saged_online_platform\build\windows\x64\runner\Release\firebase_storage_plugin.lib"; DestDir: "{app}"; Flags: ignoreversion

Source: "F:\My_Works\Flutter_Projects\koraiem_app\saged_online_platform\build\windows\x64\runner\Release\connectivity_plus_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "F:\My_Works\Flutter_Projects\koraiem_app\saged_online_platform\build\windows\x64\runner\Release\flutter_local_notifications_windows.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "F:\My_Works\Flutter_Projects\koraiem_app\saged_online_platform\build\windows\x64\runner\Release\restart_app_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion

Source: "F:\My_Works\Flutter_Projects\koraiem_app\saged_online_platform\build\windows\x64\runner\Release\file_selector_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "F:\My_Works\Flutter_Projects\koraiem_app\saged_online_platform\build\windows\x64\runner\Release\url_launcher_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "F:\My_Works\Flutter_Projects\koraiem_app\saged_online_platform\build\windows\x64\runner\Release\screen_retriever_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "F:\My_Works\Flutter_Projects\koraiem_app\saged_online_platform\build\windows\x64\runner\Release\window_size_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "F:\My_Works\Flutter_Projects\koraiem_app\saged_online_platform\build\windows\x64\runner\Release\record_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "F:\My_Works\Flutter_Projects\koraiem_app\saged_online_platform\build\windows\x64\runner\Release\syncfusion_pdfviewer_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "F:\My_Works\Flutter_Projects\koraiem_app\saged_online_platform\build\windows\x64\runner\Release\audioplayers_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion

Source: "F:\My_Works\Flutter_Projects\koraiem_app\saged_online_platform\build\windows\x64\runner\Release\WebView2Loader.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "F:\My_Works\Flutter_Projects\koraiem_app\saged_online_platform\build\windows\x64\runner\Release\pdfium.dll"; DestDir: "{app}"; Flags: ignoreversion
; data folder
Source: "F:\My_Works\Flutter_Projects\koraiem_app\saged_online_platform\build\windows\x64\runner\Release\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
[Files]
Source: "VC_redist.x64.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall

[Run]
Filename: "{tmp}\vc_redist.x64.exe"; Parameters: "/quiet /norestart"; StatusMsg: "Installing Visual C++ Redistributable..."; Check: NeedsVC

[Code]
// يتحقق إذا مكتبة VC مثبتة
function NeedsVC(): Boolean;
var
  key: string;
begin
  key := 'Software\Microsoft\VisualStudio\14.0\VC\Runtimes\x64';
  Result := not RegKeyExists(HKLM, key);
end;

